=== z-zxq-123456/myproject/personalOrion/orion/orion-base/src/main/resources/META-INF/parserMapping.dtd
<!ELEMENT mappings (mapping|baseDefine)*>
    <!ELEMENT baseDefine (globalMappingId|mappingIdSpel)+>
        <!ELEMENT globalMappingId (#PCDATA)>
        <!ELEMENT mappingIdSpel (#PCDATA)>
    <!ELEMENT mapping (in|out)>
        <!ELEMENT in (map|list|item|if)*>
        <!ELEMENT out (map|list|item|if)*>
            <!ELEMENT map (map|list|item|if)*>
            <!ELEMENT list (map|list|item|if)*>
            <!ELEMENT item ((#PCDATA))*>
            <!ELEMENT if (map|list|item|if)*>

<!ATTLIST mappings useMapping CDATA #IMPLIED> useMapping CDATA #IMPLIED>

<!ATTLIST baseDefine id CDATA #IMPLIED #REQUIRED>

<!ATTLIST mapping id CDATA #IMPLIED #REQUIRED>
<!ATTLIST mapping useMapping CDATA #IMPLIED>

<!ATTLIST in ref CDATA #IMPLIED>
<!ATTLIST in useMapping CDATA #IMPLIED>

<!ATTLIST out ref CDATA #IMPLIED>
<!ATTLIST out useMapping CDATA #IMPLIED>

<!ATTLIST map name CDATA #IMPLIED #REQUIRED>
<!ATTLIST map ref CDATA #IMPLIED #REQUIRED>
<!ATTLIST map remove CDATA #IMPLIED>

        <!ATTLIST list name CDATA #IMPLIED #REQUIRED>
        <!ATTLIST list ref CDATA #IMPLIED>
        <!ATTLIST list remove CDATA #IMPLIED>
        <!ATTLIST list alias CDATA #IMPLIED>
        <!ATTLIST list source CDATA #IMPLIED>
        <!ATTLIST list index CDATA #IMPLIED>

        <!ATTLIST item name CDATA #IMPLIED #REQUIRED>

        <!ATTLIST if test CDATA #IMPLIED #REQUIRED>

=== z-zxq-123456/myproject/personalOrion/orion/orion-base/src/test/resources/parserMapping/global-mapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--<!DOCTYPE mappings SYSTEM "http://www.dcits.com/xml/dtd/parserMapping.dtd">-->
<mappings useMapping="">
    <baseDefine id="json2mapByMapping">
        <globalMappingId>global</globalMappingId>
        <mappingIdSpel>[in][SYS_HEAD][SERVICE_CODE]+'-'+[in][SYS_HEAD][MESSAGE_TYPE]+'-'+[in][SYS_HEAD][MESSAGE_CODE]]</mappingIdSpel>
    </baseDefine>
    <baseDefine id="json2mapMapping">
        <globalMappingId>global</globalMappingId>
        <mappingIdSpel>[in][SYS_HEAD][SERVICE_CODE]+'-'+[in][SYS_HEAD][MESSAGE_TYPE]+'-'+[in][SYS_HEAD][MESSAGE_CODE]]</mappingIdSpel>
    </baseDefine>
    <mapping id="global">
        <in ref="[in]"><!--输入数据映射-->
            <map name="SYS_HEAD" ref="[in][SYS_HEAD]">
                <item name="TRAN_TIMESTAMP">T(com.dcits.galaxy.base.util.DateUtils).getDateTime()</item>
            </map>
        </in>
        <out ref="[out]">
            <map name="SYS_HEAD" ref="[out][SYS_HEAD]">
                <item name="TRAN_TIMESTAMP">T(com.dcits.galaxy.base.util.DateUtils).getDateTime()</item>
            </map>
        </out>
    </mapping>
</mappings>
